### ISSUE TITLE
Reset Password Screen don't have back button on header 

### ISSUE THREAD

**Issue by rahuljain88** [brightlayer-ui/react-native-workflows#101]
#### What are the steps to reproduce?
Go to Password Reset Screen 
On the header , there is no back button . also by clinking on cancel button , it is moving to main screen instead of back screen.

[
![123](https://user-images.githubusercontent.com/28619351/141788566-0878222a-252b-4b7a-aed7-c6171f1fc2c8.png)
](url)

**Comment by joebochill** [comment]
The close icon has been fixed with the latest icon fixes. Made a new issue for the navigation issue: https://github.com/brightlayer-ui/react-native-workflows/issues/121
