### ISSUE TITLE
Change Password screen does not have a Header

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-native-workflows#120]
#### Describe the bug
Change password screen is missing header component 

#### What is the expected behavior?
There should be a Header with a title of what the page is

#### What are the steps to reproduce?
1. Start the demo project
2. Open the change password dialog
3. Observe there is no header

#### Anything else to add?
Reported by CRDS team

**Comment by jeffvg** [comment]
this is fixed
