### ISSUE TITLE
Routes are reset when leaving the change password dialog

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-native-workflows#121]
#### Describe the bug
When you open the change password dialog and close it, you are taken back to the default route for the app.

#### What is the expected behavior?
You should be returned to the page you were on previously.

#### What are the steps to reproduce?
1. Run the demo project
2. Log in
3. Go to Page 2
4. Open the change password dialog
5. Close the change password dialog
6. Observe that you are on Home page instead of page 2

#### Anything else to add?
This is caused because the Change Password dialog is currently part of some conditional rendering. When it is visible, the rest of the app content is unmounted. When it closes, the content is re-mounted and reverts to the default route.

This was reported by Rahul on the CRDS team.

**Comment by jeffvg** [comment]
this needs verified with latest updates

**Comment by joebochill** [comment]
I can guarantee you it's not fixed. And it won't get fixed just by updating dependencies...it's an issue with how the routing is configured.
