### ISSUE TITLE
Losing focus on inputs within the create account workflows

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/react-native-workflows#151]
#### Describe the bug
After adding disablePagerAnimation={true}` to the `AuthUIContextProvider`. The user is able to move from accepting EULA page to enter Email page successfully, but there are new issues that arise:

- While entering email user suddenly loses focus of TextInputField as soon as Next button is enabled. Hence user has to click again on TextInputField to complete entering the Email.
- While entering verification code same occur after every digit entry.
- Same issue on Set password page and Enter first/last name page.

It seems like when the input value is valid then focus is lost from TextInputField

#### What is the expected behavior?
Focus should remain on input fields until the user has completed their entry

#### What are the steps to reproduce?
1. Go to either create account workflow
2. Enter data into the various fields described above
3. Observe input field loss of focus

#### Screenshots or links to minimum reproduction example

https://user-images.githubusercontent.com/13989985/168585288-6d609882-b364-495d-b4e7-2e56c39a2304.mov

**Comment by bkarambe** [comment]
This was the result of react-native-pager-view, being out of date.
