### ISSUE TITLE
Create account workflow visual consistency issues

### ISSUE THREAD

**Issue by dshiverware** [brightlayer-ui/react-native-workflows#192]
On both iOS and Android, there are visual inconsistencies within the "Create Account" workflow on larger phone screens (eg, iPhone 13 Pro Max).

**For iOS:** 
- _Verify Email step:_ There appears to be extra margins. The description text has additional margins, and the light grey underline does not extend to the screen edges as it does on other screens
- _Account Details step:_ There appears to be even more extra margins, and the text fields are smaller than others. The light grey underline does not extend to edges here either.
- **Notes:** the iPhone SE 3rd gen does not appear to have these issues (maybe because the screen is smaller). The iPhone 12 has similar problems but not as obvious as the iPhone 13 Pro Max (it also acts the same as Android in that the Create an Account email text field widens and changes the screen margins for long emails).

The screenshots below are for a iPhone 13 Pro Max. 
<img width="250" alt="iOS - Verify Email" src="https://user-images.githubusercontent.com/26386179/195931076-aa38e53a-d121-4183-b3d3-cb4f0ede0e9f.png"><img width="250" alt="iOS - Account Details" src="https://user-images.githubusercontent.com/26386179/195931085-03a25707-29cc-41f5-9b06-95b5b36b38ac.png">

**For Android:**
- _Create an Account step:_ There appears to be extra margins. The grey line does not extend to edges. But once you type, if you type a very long email, the entire screen shifts left as the text field widens. This only happens on Android.
- _Account Details step:_ There appears to be a bit of extra margins here as well, and the grey line does not extend to the edges, but not as dramatically as in iOS.

The screenshots below are for a Pixel 5.
<img width="250" alt="Android - Create Account Empty" src="https://user-images.githubusercontent.com/26386179/195931205-9d806db3-47a8-498e-8110-4a502a3a4d8a.png"><img width="250" alt="Android - Create Account Filled" src="https://user-images.githubusercontent.com/26386179/195931212-25f4647f-d647-44e6-825d-c95217e05a07.png">
<img width="250" alt="Android - Account Details" src="https://user-images.githubusercontent.com/26386179/195931216-8b1cdad4-ea9e-4adc-ac77-60e20aef848f.png">

We tested all releases back to 3.3.0 and they all seem to have these inconsistencies.

**Comment by daileytj** [comment]
I'm pretty sure these are fixed. @daileytj verify that these are fixed, otherwise... fix it!

**Comment by daileytj** [comment]
This has been fixed
