### ISSUE TITLE
Keyboard next button does not work

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-native-workflows#73]
#### Describe the bug
Since the latest custom pages were added, the keyboard next button does not move out of last name field to the country field. Once you click in to country field and press the keyboard next button it works and goes to currency field. The last custom page for job info does not display the done keyboard button.  
#### What is the expected behavior?
Keyboard next button to move to next field and to have the done button available for the last page of job info
#### What are the steps to reproduce?
1. Run through setup new account using iPad, iPhone or Android
2. Use next keyboard button from first name to last name then to country. The keyboard closes.
3. Job info page should change to use the done button once in the last field

**Comment by joebochill** [comment]
We might be able to get this to work by passing some refs around, but if it looks like it's going to be too difficult, we can hold off until a later release.
