### ISSUE TITLE
EULA checkbox is not centered on tablet

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-native-workflows#76]
#### Describe the bug
The checkbox for accepting the Eula is aligned to the far left edge of the screen.

#### What is the expected behavior?
Should be aligned to the edge of the EULA text (i.e., within the 600px max width container).

#### Environment
Tablet
		
#### Anything else to add?
This is most pronounced when viewing the workflow in landscape mode.

**Comment by huayunh** [comment]
@huayunh to double check what they did in iPPE before anyone works on this issue

**Comment by daileytj** [comment]
> @huayunh to double check what they did in iPPE before anyone works on this issue

@huayunh can you check on this? screenshot/link? Please... and thank you!
