### ISSUE TITLE
Loading Eula text should not be centered

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-native-workflows#77]
#### Describe the bug
The "Loading EULA" text appears center-aligned in the view

#### What is the expected behavior?
The text should be left align (like normal text content would be).\

**Comment by huayunh** [comment]
Ask @huayunh to check the design before you work on this issue

**Comment by daileytj** [comment]
@huayunh can you check out the design on this... maybe drop me a screenshot or link?

**Comment by huayunh** [comment]
Can we do this
![image](https://user-images.githubusercontent.com/8997218/178264252-4d0db68c-1fac-4cba-90c0-0c10b23cd62c.png)
